// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef t7_h
#define t7_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *w;
  Fl_Box *img;
  Fl_Int_Input *numParticipantes;
  Fl_Text_Display *DisplayResultado;
  Fl_Text_Display *DisplayGanhador;
protected:
  Fl_Box *Resultado;
  Fl_Button *btResetar;
  Fl_Button *btSortear;
};
#endif
