// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Output.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Input *inputLabel;
  Fl_Input *inputName;
  Fl_Button *btnClear;
  Fl_Button *btnUpdate;
  Fl_Button *btnDelete;
  Fl_Button *btnInsert;
  Fl_Browser *browser;
  Fl_Choice *chooser;
  static Fl_Menu_Item menu_chooser[];
public:
  static Fl_Menu_Item *textl_bt;
  static Fl_Menu_Item *radio_bt;
  Fl_Menu_Bar *Menu_bar;
  static Fl_Menu_Item menu_Menu_bar[];
  static Fl_Menu_Item *Project_submenu;
  static Fl_Menu_Item *NewProject;
protected:
  static Fl_Menu_Item *LoadProject;
public:
  static Fl_Menu_Item *Code_submenu;
  static Fl_Menu_Item *Generate_Code_bt;
  static Fl_Menu_Item *Set_title;
  static Fl_Menu_Item *Insert_Radio_bt;
  static Fl_Menu_Item *Help_bt;
  Fl_Output *Title_Project;
  Fl_Double_Window *NewProjectWindow;
  Fl_Input *ProjectName_input;
  Fl_Input *ProjectFile_input;
  Fl_Button *New_Pro_OK_bt;
  Fl_Button *New_Pro_Cancel_bt;
  Fl_Double_Window *Radio_bt_Window;
  Fl_Input *Radio_bt_1;
  Fl_Input *Radio_bt_2;
  Fl_Input *Radio_bt_3;
  Fl_Button *Radio_Update_bt;
  Fl_Button *Radio_cancel_bt;
  Fl_Button *insert_bt_Radio;
  Fl_Double_Window *Title_window;
  Fl_Input *Web_page_name;
  Fl_Input *Web_page_title;
  Fl_Button *Title_save_bt;
  Fl_Button *Title_cancel_bt;
};
#endif
