// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

Fl_Menu_Item UserInterface::menu_chooser[] = {
 {"Text Input", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Radio Input", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::textl_bt = UserInterface::menu_chooser + 0;
Fl_Menu_Item* UserInterface::radio_bt = UserInterface::menu_chooser + 1;

Fl_Menu_Item UserInterface::menu_Menu_bar[] = {
 {"Project", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"New Project", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Project", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Code", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Generate Code", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Set Title", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Insert Radio Button", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::Project_submenu = UserInterface::menu_Menu_bar + 0;
Fl_Menu_Item* UserInterface::NewProject = UserInterface::menu_Menu_bar + 1;
Fl_Menu_Item* UserInterface::LoadProject = UserInterface::menu_Menu_bar + 2;
Fl_Menu_Item* UserInterface::Code_submenu = UserInterface::menu_Menu_bar + 4;
Fl_Menu_Item* UserInterface::Generate_Code_bt = UserInterface::menu_Menu_bar + 5;
Fl_Menu_Item* UserInterface::Set_title = UserInterface::menu_Menu_bar + 6;
Fl_Menu_Item* UserInterface::Insert_Radio_bt = UserInterface::menu_Menu_bar + 7;
Fl_Menu_Item* UserInterface::Help_bt = UserInterface::menu_Menu_bar + 9;

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(535, 565, "Code Generator");
    w->color((Fl_Color)48);
    w->user_data((void*)(this));
    { inputLabel = new Fl_Input(85, 111, 360, 24, "Label:");
    } // Fl_Input* inputLabel
    { inputName = new Fl_Input(85, 141, 360, 24, "Name:");
    } // Fl_Input* inputName
    { btnClear = new Fl_Button(35, 245, 100, 25, "Clear");
    } // Fl_Button* btnClear
    { btnUpdate = new Fl_Button(159, 245, 100, 25, "Update");
    } // Fl_Button* btnUpdate
    { btnDelete = new Fl_Button(280, 245, 100, 25, "Delete");
    } // Fl_Button* btnDelete
    { btnInsert = new Fl_Button(397, 245, 100, 25, "Insert");
    } // Fl_Button* btnInsert
    { browser = new Fl_Browser(35, 286, 470, 243);
      browser->type(2);
    } // Fl_Browser* browser
    { chooser = new Fl_Choice(85, 170, 360, 25, "Type: ");
      chooser->down_box(FL_BORDER_BOX);
      chooser->menu(menu_chooser);
    } // Fl_Choice* chooser
    { Menu_bar = new Fl_Menu_Bar(0, 0, 535, 20, "Menu_bar");
      Menu_bar->menu(menu_Menu_bar);
    } // Fl_Menu_Bar* Menu_bar
    { Title_Project = new Fl_Output(130, 40, 295, 50);
      Title_Project->box(FL_GTK_DOWN_BOX);
      Title_Project->color(FL_DARK1);
      Title_Project->labelfont(1);
      Title_Project->labelsize(25);
      Title_Project->labelcolor(FL_INACTIVE_COLOR);
      Title_Project->textfont(1);
      Title_Project->textsize(25);
    } // Fl_Output* Title_Project
    w->end();
  } // Fl_Double_Window* w
  { NewProjectWindow = new Fl_Double_Window(390, 165, "New Project");
    NewProjectWindow->user_data((void*)(this));
    { ProjectName_input = new Fl_Input(140, 22, 225, 28, "Project Name:  ");
    } // Fl_Input* ProjectName_input
    { ProjectFile_input = new Fl_Input(140, 56, 225, 26, "Project File:      ");
    } // Fl_Input* ProjectFile_input
    { New_Pro_OK_bt = new Fl_Button(60, 110, 130, 35, "OK");
    } // Fl_Button* New_Pro_OK_bt
    { New_Pro_Cancel_bt = new Fl_Button(200, 110, 130, 35, "CANCEL");
    } // Fl_Button* New_Pro_Cancel_bt
    NewProjectWindow->end();
  } // Fl_Double_Window* NewProjectWindow
  { Radio_bt_Window = new Fl_Double_Window(340, 180);
    Radio_bt_Window->user_data((void*)(this));
    { Radio_bt_1 = new Fl_Input(130, 17, 180, 28, "Radio button 1:");
    } // Fl_Input* Radio_bt_1
    { Radio_bt_2 = new Fl_Input(130, 51, 180, 27, "Radio button 2:");
    } // Fl_Input* Radio_bt_2
    { Radio_bt_3 = new Fl_Input(130, 87, 180, 29, "Radio button 3:");
    } // Fl_Input* Radio_bt_3
    { Radio_Update_bt = new Fl_Button(50, 130, 110, 35, "Update");
    } // Fl_Button* Radio_Update_bt
    { Radio_cancel_bt = new Fl_Button(175, 130, 110, 35, "Cancel");
    } // Fl_Button* Radio_cancel_bt
    { insert_bt_Radio = new Fl_Button(40, 130, 125, 40, "Insert");
    } // Fl_Button* insert_bt_Radio
    Radio_bt_Window->end();
  } // Fl_Double_Window* Radio_bt_Window
  { Title_window = new Fl_Double_Window(320, 165, "Set Title");
    Title_window->user_data((void*)(this));
    { Web_page_name = new Fl_Input(140, 24, 160, 31, "Web Page Name:");
    } // Fl_Input* Web_page_name
    { Web_page_title = new Fl_Input(140, 62, 160, 28, "Web Page Title:   ");
    } // Fl_Input* Web_page_title
    { Title_save_bt = new Fl_Button(70, 110, 90, 40, "Save");
    } // Fl_Button* Title_save_bt
    { Title_cancel_bt = new Fl_Button(175, 110, 90, 40, "Cancel");
    } // Fl_Button* Title_cancel_bt
    Title_window->end();
  } // Fl_Double_Window* Title_window
}
